apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-secrets
  namespace: default
spec:
  provider: azure
  secretObjects:
  - secretName: db-secret
    type: Opaque
    data:
    - key: dbuser
      objectName: dbuser
    - key: dbpassword
      objectName: dbpassword
    - key: databaseurl
      objectName: databaseurl
    - key: databasename
      objectName: databasename
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"  # ✅ You are using system-assigned identity from AKS
    userAssignedIdentityID: ""    # ❌ Not needed because you're not using a UAMI
    keyvaultName: "gowridbkeys"   # ✅ from your Terraform: azurerm_key_vault.kv.name
    tenantId: "ec6e8fb5-4284-4351-b9af-a68b18acee8e" # ✅ consistent with your `data.azurerm_client_config.current`
    objects: |
      array:
        - objectName: dbuser
          objectType: secret
        - objectName: dbpassword
          objectType: secret
        - objectName: databaseurl
          objectType: secret
        - objectName: databasename
          objectType: secret
