apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-secrets
  namespace: default
spec:
  provider: azure
  secretObjects:
    - secretName: db-secret
      type: Opaque
      data:
        - objectName: dbuser
          key: dbuser
        - objectName: dbpassword
          key: dbpassword
        - objectName: databaseurl
          key: databaseurl
        - objectName: databasename
          key: databasename
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    keyvaultName: "moneyfikeyvault"
    tenantId: "ec6e8fb5-4284-4351-b9af-a68b18acee8e"
    objects: |
      array:
        - |
          objectName: dbuser
          objectType: secret
        - |
          objectName: dbpassword
          objectType: secret
        - |
          objectName: databaseurl
          objectType: secret
        - |
          objectName: databasename
          objectType: secret
